name: Docker Push

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        export buildtag=$(date +%s)
        docker build . -t skydome/dockerflutter
        docker tag skydome/dockerflutter skydome/dockerflutter:latest
        docker tag skydome/dockerflutter skydome/dockerflutter:$buildtag
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username="${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push sydome/dockerflutter:latest
        docker push sydome/dockerflutter:$buildtag
